--- Snowflake uses RBAC (Role Based Access Control) as one of 2 Access Control methods
--- USE ACCOUNTADMIN which is SYSADMIN + SECURITYADMIN
USE ROLE ACCOUNTADMIN;

SHOW USERS;

CREATE ROLE EDW;

GRANT ROLE EDW TO USER MICHAEL777;

SHOW ROLES;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE EDW;
GRANT USAGE ON DATABASE CITIBIKE TO ROLE EDW;
GRANT USAGE ON DATABASE WEATHER TO ROLE EDW;
GRANT USAGE ON SCHEMA PUBLIC TO ROLE EDW;

USE ROLE EDW;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE CITIBIKE;
USE SCHEMA PUBLIC;

SELECT TOP 10 *
FROM TRIPS;

