--- STREAMS used to track changes on table data such as INSERT / UPDATE / DELETE

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE DEMO_DB;
USE SCHEMA DEMO_SCHEMA;

SHOW TABLES;

SELECT *
FROM DEMO_TABLE;

SHOW STREAMS; 

--- CREATE STREAM ON ANY TABLE
CREATE STREAM MY_STREAM 
ON TABLE DEMO_TABLE;

SHOW STREAMS; 

--- VIEW STREAM TO CHECK FOR ANY CHANGES
SELECT *
FROM MY_STREAM;


INSERT INTO DEMO_TABLE (NAME, AGE)
VALUES ('MY MANUAL INSERT','99');

SELECT *
FROM MY_STREAM;

INSERT INTO DEMO_TABLE (NAME, AGE)
VALUES ('MY MANUAL INSERT2','101');

SHOW TASKS;

--- CREATE NEW TASK TO UPDATE STREAM
CREATE TASK MYTASK2 
    WAREHOUSE=COMPUTE_WH 
    SCHEDULE='5 MINUTES'
AS 
    INSERT INTO DEMO_TABLE (NAME, AGE) 
    VALUES ('MAXI2','200');
    
EXECUTE TASK MYTASK2;
EXECUTE TASK MYTASK;

ALTER TASK IF EXISTS  MYTASK2 RESUME;

