--- LET'S POWER DOWN UNUSED WAREHOUSES
--- Charges are build on TOTAL running time of Warehouse, min 60 sec.  
--- Charges are not based on running time of SQL COMMANDS alone.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

SHOW WAREHOUSES;

--- IF SUSPENDED USE IT.
USE WAREHOUSE SCU_COMPUTE;

ALTER WAREHOUSE SCU_COMPUTE 
SET WAREHOUSE_SIZE = MEDIUM;

SHOW WAREHOUSES;

ALTER WAREHOUSE SCU_COMPUTE 
SET WAREHOUSE_SIZE = XSMALL;

ALTER WAREHOUSE SCU_COMPUTE RESUME;

SHOW WAREHOUSES;

ALTER WAREHOUSE SCU_COMPUTE SUSPEND;

SHOW WAREHOUSES;

--- CREATE WAREHOUSE 
--- SET AUTO_SUSPEND=300 / 5min
--- SET AUTO_RESUME=TRUE
CREATE WAREHOUSE MY_COST_TEST
AUTO_SUSPEND=300
AUTO_RESUME=TRUE;

SHOW WAREHOUSES;


USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

ALTER WAREHOUSE MY_COST_TEST SUSPEND;

DROP WAREHOUSE MY_COST_TEST;
